using AsiPisomka;

Console.WriteLine("Person:");
Console.WriteLine();
Person p = new Person("Peter", "Cmorik", 36, 1.87);
Console.WriteLine(p);
Console.WriteLine("Employee:");
Console.WriteLine();
Emloyee e = new Emloyee("Emil", "Dakar", 36, 1.89, 1500);
Console.WriteLine(e);
Console.WriteLine("Firm:");
Console.WriteLine();
Firm firm = new();
firm.Employees.Add(e);
firm.Employees.Add(new Emloyee("Anna", "Maria", 21, 1.80, 1750));
firm.Employees.Add(new Emloyee("Fero", "Biely", 34, 2.00, 200));
firm.Employees.Add(new Emloyee("Michal", "Modry", 44, 2.01, 1200));
firm.Employees.Add(new Emloyee("Adrian", "Zeleny", 22, 1.85, 1000));
firm.Employees.Add(new Emloyee("Jakub", "Lajos", 51, 1.55, 900));
firm.Employees.Add(new Emloyee("Tomas", "Fik", 25, 1.91, 2100));
firm.Employees.Add(new Emloyee("Julia", "Mala", 27, 1.60, 1950));
firm.Employees.Add(new Emloyee("Zuzana", "Biela", 39, 1.55, 1650));
firm.Employees.Add(new Emloyee("Samuel", "Silny", 37, 1.65, 1300));
Console.WriteLine("1200+");
firm.PrintEmployeesWithIncome(1200);
